### ISSUE TITLE
login

### ISSUE THREAD

**Issue by itscoooldeep** [sumeyye-uzgor/TaskManagementSystem#1]
login is not working
and sign up page is not given

**Comment by sumeyye-uzgor** [comment]
Hi, you may think that it is working with company mails and mails are assigning from backend with user addition. But i will check about login part.
Using mary@company.com or john@company.com you can login but it may not work. I will check it again but solution may take some parti.

**Comment by itscoooldeep** [comment]
i also clone backend 
but dont know how to connect

**Comment by sumeyye-uzgor** [comment]
Are you trying to do same task?
Saygılarımla,

Best Regards,

Sümeyye ÜZGÖR

Jr. Frontend Developer

Istanbul, Turkey

**Comment by itscoooldeep** [comment]
Yes can i get ur instagram id so we can txt faster this process is slow

**Comment by sumeyye-uzgor** [comment]
Discord me pls if you have. My discord id is Sumeyye#1270. But if you dont
have discord, then mail me ***@***.***

**Comment by itscoooldeep** [comment]
CoolDeep#3382 my discord id i sent request

**Comment by itscoooldeep** [comment]
Its working
